version: '3.8'

services:
  mongodb:
    image: mongodb/mongodb-atlas-local
    container_name: mongodb-baseapi
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=mongoAtlasAdmin
      - MONGODB_INITDB_ROOT_PASSWORD=HOyYMG1KoDfuYLf7IqqP
    ports:
      - 27018:27017
    networks:
      - net

networks:
  net:
    driver: bridge
